# action.yml
name: Validate Recipe
description: Validate a recipe file using the provided schema.
inputs:
  json-file:
    description: 'Path to the JSON file to validate.'
    required: true
  schema-file:
    description: 'Path to the schema file for validation.'
    required: true
outputs:
  json:
    description: 'The content of the JSON file.'
  isValid:
    description: 'The validation status (true or false).'
runs:
  using: 'node12'
  main: 'index.js'
